language: minimal
branches:
  only:
  - master
addons:
  apt:
    packages:
    - tree
env:
  global:
  - REPO=Country-IP-Blocks
  - LC_ALL=C.UTF-8
script:
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch origin gh-pages
- git checkout gh-pages
- git checkout master -- generate.sh
- ./generate.sh && rm generate.sh
- sha256sum -b *.txt > sha256sums.txt
- curl -sL https://gist.github.com/HackingGate/9e8169c7645b074b2f40c959ca20d738/raw/3ae3913f308d9cf34962ac3488b5973a2fbe1a95/restore_last_git_modified_time.sh | sh
- tree -H '.' -L 1 -h -D --timefmt '%Y-%m-%d %H:%M:%S %Z' --noreport --charset utf-8 -T 'Country IP Blocks' -o index.html
- cat github-corner.html >> index.html
- sed -i "s/your-url/github.com\/${GH_USER}\/${REPO}/g" index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  keep_history: true
