language: minimal
branches:
  only:
  - master
addons:
  apt:
    packages:
    - tree
env:
  global:
  - REPO=Country-IP-Blocks
  - LC_ALL=C.UTF-8
script:
- git clone https://${GH_USER}:${GH_TOKEN}@github.com/${GH_USER}/${REPO}.git --branch gh-pages --single-branch gh-pages
- cd gh-pages
- $OLDPWD/generate.sh
- git config user.name "${GIT_NAME}"
- git config user.email "${GIT_EMAIL}"
- git add delegated-*-latest.txt country_code.txt *_IPv*
- curl -sL https://gist.github.com/HackingGate/9e8169c7645b074b2f40c959ca20d738/raw/89a9a48db1f494ffee0b7aa552ce35f18ae29091/restore_last_git_modified_time.sh | sh
- tree -H '.' -L 1 -D --noreport --charset utf-8 > index.html
- sed -i "s/Directory Tree/${REPO}/g" index.html
- cat github-corner.html >> index.html
- sed -i "s/your-url/github.com\/${GH_USER}\/${REPO}/g" index.html
- git add index.html
- git status
- DATE=$(date)
- git diff --quiet && git diff --staged --quiet && echo 'Nothing to commit' || git commit -m "Generated on [$DATE]"
- git push -q origin gh-pages
